name: Lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install ansible-lint
          ansible-galaxy collection install community.vmware ansible.posix

      - name: Run ansible-lint
        run: ansible-lint playbooks/*.yml
